In [36]:
import numpy as np
import numba
import random
import time


In [37]:
arr = np.zeros((1000,1000))
def loops ():   
    for i in range(1000-1):
        for j in range(1000-1):
            arr[i,j] = np.random.randint(1,200)
    return arr


In [38]:
arr2 = np.zeros((1000,1000))
def jit_loops ():   
    for i in range(1000-1):
        for j in range(1000-1):
            arr2[i,j] = np.random.randint(1,200)

            

In [39]:
def regne(x):
    for i in range(len(x)):
        for j in range(len(x)):
            x[i,j] = x[i,j]*3+4
    return x

In [40]:
@numba.jit
def regnejit(x):
    for i in range(len(x)):
        for j in range(len(x)):
            x[i,j] = x[i,j]*3+4
    return x

In [47]:
ny = loops()
before = time.perf_counter()
regne(ny)
after = time.perf_counter()
print('diff:', after-before)



diff: 0.8948359070000151


In [45]:
ny2 = loops()
before = time.perf_counter()
regnejit(ny2)
after = time.perf_counter()
print('diff:', after-before)

diff: 0.0011467269999911878


In [43]:
print(arr)


[[493. 523. 148. ...  85. 589.  16.]
 [451. 154. 403. ... 265. 334.  16.]
 [589. 247. 166. ... 208. 415.  16.]
 ...
 [589. 112. 499. ... 454. 478.  16.]
 [535. 451. 127. ... 448. 412.  16.]
 [ 16.  16.  16. ...  16.  16.  16.]]
